export const COMMUNITY_IS_OPENED_QRCODE = 'COMMUNITY_IS_OPENED_QRCODE' // 是否显示二维码

export const COMMUNITY_BUSINESS_DETAIL = 'COMMUNITY_BUSINESS_DETAIL'
export const SERVICE_SITE_DETAIL = 'SERVICE_SITE_DETAIL'
export const BUSINESS_APPLY_UPDATE = 'BUSINESS_APPLY_UPDATE' // 更新社区商户创建信息
export const SERVICE_SITE_APPLY_UPDATE = 'SERVICE_SITE_APPLY_UPDATE' // 更新社区服务站创建信息